workflow:
  version: "2.0"
  last_updated: "2026-02-17T01:40:00+09:00"

  last_session_summary: |
    【今回のセッションでやったこと】
    - プロジェクト全体に残っていた `Desktop` パスを `Developer` に一括置換し、環境を完全復旧。
    - システム (Hard) と人格 (Soft) の分離を完了し、System Kernel をリファクタリング。
    - `.agent/rules/` 内の全ルールファイルから人格依存表現を除去し、システム定義として中立化。
    - `06-character-rina.md` をポインタファイルに変更し、`person.md` による人格管理を確立。

    【次にやること】
    - `.agent/workflows/` 内のワークフローのリファクタリング（中立化）。
    - 各サブプロジェクト（new-worldなど）における個別ルールの整備と整合性確認。

  progress:
    current_phase:
      number: 12
      name: "System Kernel Refactoring (Persona Separation)"
      status: "in_progress"
    
    current_task:
      description: "Workflow Rules Refactoring"
      started_at: "2026-02-17T01:40:00+09:00"
    
    completed_phases:
      - phase: 10
        name: "Uber Data Pipeline 統合"
        completed_at: "2026-02-07"
      - phase: 11
        name: "Environment Migration & Optimization"
        completed_at: "2026-02-16"

  decisions:
    adopted:
      - id: "D013"
        date: "2026-02-16"
        decision: "パッケージマネージャーを pnpm に完全統一"
        reason: "ディスク容量削減、インストール高速化、Monorepo構成への布石のため"
      
      - id: "D014"
        date: "2026-02-16"
        decision: "ZG_PROJECT 直下の node_modules は配置しない"
        reason: "各プロジェクトごとの独立性を保つため（現状はWorkspace構成ではない）"

      - id: "D015"
        date: "2026-02-16"
        decision: "ルール上の npm/yarn 完全排除"
        reason: "開発フローを標準化し、誤用を防ぐため"
        
      - id: "D016"
        date: "2026-02-16"
        decision: "ディレクトリ移動時は venv を完全再構築する"
        reason: "venv 内の絶対パス参照が壊れるため、コピーや移動ではなく再作成が必須"

      - id: "D017"
        date: "2026-02-16"
        decision: "人格定義のXML化と分離"
        reason: "システムと人格の責務分離、構造化による読み込み精度向上のため"

      - id: "D018"
        date: "2026-02-16"
        decision: "RINA.mdの廃止"
        reason: "person.mdへの移行完了のため"

      - id: "D019"
        date: "2026-02-16"
        decision: ".agent/rules のSystem Definition化"
        reason: "ルールファイルから人格要素を排除し、純粋なシステム仕様定義として機能させるため"

  features:
    completed:
      - id: "F010"
        name: "pnpm移行 & ディレクトリクリーンアップ"
        status: "done"
        completed_at: "2026-02-16T12:20:00+09:00"
      - id: "F011"
        name: "pnpm強制ルールの適用"
        status: "done"
        completed_at: "2026-02-16T12:25:00+09:00"
      - id: "F012"
        name: "Desktop→Developerパス完全移行"
        status: "done"
        completed_at: "2026-02-16T23:25:00+09:00"
      - id: "F013"
        name: "Persona Separation (GEMINI.md refactoring)"
        status: "done"
        completed_at: "2026-02-16T23:20:00+09:00"
      - id: "F014"
        name: "XML Persona Definition (person.md)"
        status: "done"
        completed_at: "2026-02-16T23:20:00+09:00"
      - id: "F015"
        name: "Rules Layer Refactoring (System Definition)"
        status: "done"
        completed_at: "2026-02-16T23:55:00+09:00"

  cautions:
    - id: "C006"
      category: "環境"
      content: "Google Apps Script プロジェクトは @google/clasp を使用する"
      reason: "無印の clasp パッケージは pnpm で解決できない場合があるため"
    - id: "C007"
      category: "Python"
      content: "pip install でエンコーディングエラーが出る場合は PYTHONIOENCODING=utf-8 を指定する"
      reason: "環境によってはデフォルトエンコーディングが正しく認識されずインストールが失敗するため"
