workflow:
  version: "2.0"
  last_updated: "2026-02-28T15:15:00+09:00"

  last_session_summary: |
    【今回のセッションで話したこと・決まったこと】
    - `/images` ワークフローの全体的なブラッシュアップを実施。
    - 保存先を Desktop に固定し、生成後に `cd` 必須の移動コマンドを提示する「物理的確実性」を強化。
    - `/zerogra-assets` フォルダとの強力な連携（アセットスキャン、テンプレート永続化）を実装。
    - ヒアリングを「10パターン提案（コンセプト・カラー込）」へ高度化。
    - 「サンプル先行出し → フィードバック → テンプレート修正 → 本番量産」という精密な生成プロセスを構築。
    - 構図・アスペクト比の確認を必須ステップとして定義し、AIの独断を排除。
    
    【今後の方向性・これから決めること】
    - 新しくなった `/images` を実戦投入し、`/zerogra-assets/prompt-template` に蓄積されるレシピの質を向上させる。
    - 生成された画像の「文字入れ（日本語）」の精度をさらに上げるためのプロンプトハックの蓄積。
    
    【次にやること（実行順序）】
    1. 新しい `/images` を使って、具体的な制作物（LP用バナーなど）の生成を開始する。
    2. 生成過程で得られたプロンプトのコツを `KNOWLEDGE.md` に追記し、ワークフローをさらに自己進化させる。

  progress:
    current_phase:
      number: 17
      name: "[/images] ワークフロー革新 & 自己進化基盤の構築"
      status: "done"

    current_task:
      description: "セッション保存と知見の永続化"
      started_at: "2026-02-28T14:57:00+09:00"

    completed_phases:
      - phase: 10
        name: "Uber Data Pipeline 統合"
        completed_at: "2026-02-07"
      - phase: 11
        name: "Environment Migration & Optimization"
        completed_at: "2026-02-16"
      - phase: 12
        name: "System Kernel Refactoring (Persona Separation)"
        completed_at: "2026-02-17"
      - phase: 13
        name: "Master Agent Architecture Update"
        completed_at: "2026-02-23"
      - phase: 14
        name: "Establishment of Dual-Core Workflow"
        completed_at: "2026-02-23"
      - phase: 15
        name: "ECC Skills Optimization & Integration"
        completed_at: "2026-02-23"
      - phase: 16
        name: "ECC v2 実走検証 & sf-maker 構築"
        completed_at: "2026-02-24"
      - phase: 17
        name: "[/images] ワークフロー革新 & 自己進化基盤の構築"
        completed_at: "2026-02-28"

    next_tasks:
      - "新しい /images を使った実戦投入とプロンプトテンプレートの蓄積"

  decisions:
    adopted:
      - id: "D024"
        date: "2026-02-23"
        decision: "Claude Skills のグローバル全面展開 (ECC v2)"
        reason: "あらゆるプロジェクトで一貫したプロ品質の助言（最強思想）を自動発動させるため"
      - id: "D025"
        date: "2026-02-23"
        decision: "スキルトリガーの『思想×精度』両立方針"
        reason: "装飾語による思想注入と、技術用語による発動精度の両立がClaudeの能力最大化に不可欠なため"
      - id: "D026"
        date: "2026-02-23"
        decision: "Phase 16 戦略プランの確定"
        reason: "新スキル環境の検証と sf-maker 構築に向けた方針についてユーザー合意を得たため"
      - id: "D027"
        date: "2026-02-24"
        decision: "sf-maker スキルの導入 — スキル作成前の既存調査を強制化"
        reason: "ECC スキル群が45本に増加し、無計画な追加による重複・劣化を防ぐ品質ゲートが必要になったため"
      - id: "D028"
        date: "2026-02-26"
        decision: "/save-session を情報の粒度を明確に分けた『追記・蓄積型』へとシフト"
        reason: "既存のAIが上書きでコンテキストをロストするアンチパターンを防ぐため"
      - id: "D029"
        date: "2026-02-26"
        decision: "セーブデータの長さ無制限・SDK水準の徹底化ルールの追加"
        reason: "「簡潔さよりも詳細、網羅性、再現性が最優先」という要求に応え、次担当のAIがいまの人間と『全く同じ解像度』で再開できるようにするため"
      - id: "D030"
        date: "2026-02-28"
        decision: "/images の保存フローを Desktop + 手動移動（cd明示）に統一"
        reason: "macOSのアクセス権限エラーを回避し、かつユーザーが成果物を即座に視認・操作できるようにするため"
      - id: "D031"
        date: "2026-02-28"
        decision: "プロンプトテンプレートの永続化先を /zerogra-assets/prompt-template に固定"
        reason: "プロジェクトを横断して一貫した高品質な画像生成レシピを共有・再利用可能な資産にするため"
      - id: "D032"
        date: "2026-02-28"
        decision: "生成前のプラン・プロンプト明示フローの導入"
        reason: "Imagen 3 等の高価な生成リトライを減らし、意図の不一致を未然に防ぐため"

  features:
    completed:
      - id: "F019"
        name: "ECC Strong Descriptions (44 skills)"
        status: "done"
        completed_at: "2026-02-23T20:10:00+09:00"
      - id: "F020"
        name: "ECC Global Installation"
        status: "done"
        completed_at: "2026-02-23T20:41:00+09:00"
      - id: "F021"
        name: "ECC Playbook & Hello-Claude Integration"
        status: "done"
        completed_at: "2026-02-23T20:17:00+09:00"
      - id: "F022"
        name: "ECC v2 Quality Gate (978 tests)"
        status: "done"
        completed_at: "2026-02-24T00:00:00+09:00"
      - id: "F023"
        name: "sf-maker (Search First Maker) スキル"
        status: "done"
        completed_at: "2026-02-24T00:00:00+09:00"
      - id: "F024"
        name: "/images 自己進化型ワークフロー v2.5"
        status: "done"
        completed_at: "2026-02-28T15:10:00+09:00"

  cautions:
    - id: "C009"
      category: "設計"
      content: "description内の技術キーワードを削りすぎないこと"
      reason: "装飾語だけではClaudeの発動判断が鈍るため、具体的トリガーフレーズの維持が必須"
    - id: "C010"
      category: "画像生成"
      content: "アスペクト比と照明構図は必ずユーザーに選択させる"
      reason: "これらはデザインの根幹に関わり、AIの推測が外れた場合の手戻りが大きいため"
