workflow:
  version: "2.0"
  last_updated: "2026-02-23T14:49:00+09:00"

  last_session_summary: |
    【Phase 14: デュアルコア・ワークフロー（戦略と実行の分離）の確立】
    - ブラウザ（戦略）でプランを立て、CLI（実行）で全自動完遂する運用スタイルを正式採用。
    - CLI側の Claude Code 用に `/run-plan` カスタムコマンドを作成し、グローバル（`~/.claude/commands/`）へ配置。
    - CLI側のグローバル設定（`CLAUDE.md`, `settings.json`）をアップデート。
    - `dual-core-test` プロジェクトにて、ライブラリ導入からサーバー構築、バックグラウンド検証までの全自動実行に成功。
    - システムプロトコル（person.md, KNOWLEDGE.md）に新プロトコルを永続化。

    【次にやること】
    - 本番プロジェクトへの `/dual-core` フロー適用
    - 並列開発（複数ターミナルでの同時実行）の実践

  progress:
    current_phase:
      number: 14
      name: "Establishment of Dual-Core Workflow"
      status: "done"

    current_task:
      description: "セッション保存と知見の永続化"
      started_at: "2026-02-23T14:24:00+09:00"

    completed_phases:
      - phase: 10
        name: "Uber Data Pipeline 統合"
        completed_at: "2026-02-07"
      - phase: 11
        name: "Environment Migration & Optimization"
        completed_at: "2026-02-16"
      - phase: 12
        name: "System Kernel Refactoring (Persona Separation)"
        completed_at: "2026-02-17"
      - phase: 13
        name: "Master Agent Architecture Update"
        completed_at: "2026-02-23"

  decisions:
    adopted:
      - id: "D022"
        date: "2026-02-23"
        decision: "デュアルコア・ワークフロー（戦略と実行の分離）の正式採用"
        reason: "コスト削減、実行精度の向上、および複数プロジェクトの並列開発を可能にするため"
      - id: "D023"
        date: "2026-02-23"
        decision: "Claude Code CLI 設定のグローバル化（~/.claude/）"
        reason: "複数プロジェクト間で共通のペルソナ、コマンド、通知システムを維持し、管理を容易にするため"

  features:
    completed:
      - id: "F016"
        name: "Dual-Core Workflow Protocol"
        status: "done"
        completed_at: "2026-02-23T14:45:00+09:00"
      - id: "F017"
        name: "Global Claude Code CLI Configuration"
        status: "done"
        completed_at: "2026-02-23T14:40:00+09:00"
      - id: "F018"
        name: "Automated Plan Execution Tool (/run-plan)"
        status: "done"
        completed_at: "2026-02-23T14:30:00+09:00"

  cautions:
    - id: "C008"
      category: "運用"
      content: "実行コア（CLI）へのプラン提示は prompt/plan-fixed/ 経由で行う"
      reason: "固定されたプランファイルを介すことで、AIの独断を防ぎ、設計通りの実行を担保するため"
