workflow:
  version: "2.0"
  last_updated: "2026-02-24T00:00:00+09:00"

  last_session_summary: |
    【今回のセッションで話したこと・決まったこと】
    - `/save-session` ワークフローのブラッシュアップについて議論。
    - コンテキストを失わずに確実に引き継ぐために、保存先ごとの「情報の粒度」を明確に定義。
    - さらに「簡潔さよりも詳細、網羅性、再現性が最優先」「長さは制限しない」「公式ドキュメント/SDK水準」というAI向けの厳しい制約ルールを追加するリクエストを受けた。
    - セッションの記憶を `WORKFLOW.yaml`（議論・決定・次回）、`KNOWLEDGE.md`（反省・教訓）、`DATABASE.md` / `ARCHITECTURE.yaml`（データ・ファイル構造）へ詳細に分割して**追記（蓄積型）**する運用へ完全移行。「初めて見た人が同じ解像度で理解できるか」を最優先指標（Core Metric）として設定。
    - ブラッシュアップの過程で一度失われてしまったAI向けの具体的な「YAMLテンプレート」や「出力プレビュー」「// turboコマンド」をすべて復元し、そこに新しい蓄積・詳細化の概念を統合して、より強固なワークフローとして再構築。
    - セーブデータ（YAML）はどれだけ長くなっても構わず、システムの根幹をなす公式ドキュメント（SDK相当の仕様書）として扱うことを明示的に仕様化して `save-session.md` に追記。
    
    【今後の方向性・これから決めること】
    - 今後すべてのプロジェクトにおいて、この新しい `/save-session` ワークフローを用いて、過去の文脈や「なぜそう決まったか」という背景理由を100%保持した高解像度なコンテキスト引き継ぎを実現し、AIの実装ズレや記憶喪失を根絶していく。
    - 新しい詳細な仕様で運用を回してみて、実際に各管理ファイルがどこまで蓄積されていくかのモニタリング。
    
    【次にやること（実行順序）】
    1. 次回の開発セッション（進行中の別プロジェクトなど）で、この新しくなった `/save-session` をさっそく試運転し、不足なくコンテキストが保持されるかを実際に体験する。

  progress:
    current_phase:
      number: 16
      name: "ECC v2 実走検証 & sf-maker 構築"
      status: "done"

    current_task:
      description: "セッション保存と知見の永続化"
      started_at: "2026-02-23T19:20:00+09:00"

    completed_phases:
      - phase: 10
        name: "Uber Data Pipeline 統合"
        completed_at: "2026-02-07"
      - phase: 11
        name: "Environment Migration & Optimization"
        completed_at: "2026-02-16"
      - phase: 12
        name: "System Kernel Refactoring (Persona Separation)"
        completed_at: "2026-02-17"
      - phase: 13
        name: "Master Agent Architecture Update"
        completed_at: "2026-02-23"
      - phase: 14
        name: "Establishment of Dual-Core Workflow"
        completed_at: "2026-02-23"
      - phase: 15
        name: "ECC Skills Optimization & Integration"
        completed_at: "2026-02-23"
      - phase: 16
        name: "ECC v2 実走検証 & sf-maker 構築"
        completed_at: "2026-02-24"

    next_tasks:
      - "次回の開発セッション（別プロジェクト等）で新 save-session の試運転とコンテキスト保持の確認"

  decisions:
    adopted:
      - id: "D024"
        date: "2026-02-23"
        decision: "Claude Skills のグローバル全面展開 (ECC v2)"
        reason: "あらゆるプロジェクトで一貫したプロ品質の助言（最強思想）を自動発動させるため"
      - id: "D025"
        date: "2026-02-23"
        decision: "スキルトリガーの『思想×精度』両立方針"
        reason: "装飾語による思想注入と、技術用語による発動精度の両立がClaudeの能力最大化に不可欠なため"
      - id: "D026"
        date: "2026-02-23"
        decision: "Phase 16 戦略プランの確定"
        reason: "新スキル環境の検証と sf-maker 構築に向けた方針についてユーザー合意を得たため"
      - id: "D027"
        date: "2026-02-24"
        decision: "sf-maker スキルの導入 — スキル作成前の既存調査を強制化"
        reason: "ECC スキル群が45本に増加し、無計画な追加による重複・劣化を防ぐ品質ゲートが必要になったため。search-first の『コード版』に相当するスキル作成ガバナンスとして機能させる。"
      - id: "D028"
        date: "2026-02-26"
        decision: "/save-session を情報の粒度を明確に分けた『追記・蓄積型』へとシフト"
        reason: "既存のAIが上書きでコンテキストをロストするアンチパターンを防ぐため"
      - id: "D029"
        date: "2026-02-26"
        decision: "セーブデータの長さ無制限・SDK水準の徹底化ルールの追加"
        reason: "「簡潔さよりも詳細、網羅性、再現性が最優先」という要求に応え、次担当のAIがいまの人間と『全く同じ解像度』で再開できるようにするため"

  features:
    completed:
      - id: "F019"
        name: "ECC Strong Descriptions (44 skills)"
        status: "done"
        completed_at: "2026-02-23T20:10:00+09:00"
      - id: "F020"
        name: "ECC Global Installation"
        status: "done"
        completed_at: "2026-02-23T20:41:00+09:00"
      - id: "F021"
        name: "ECC Playbook & Hello-Claude Integration"
        status: "done"
        completed_at: "2026-02-23T20:17:00+09:00"
      - id: "F022"
        name: "ECC v2 Quality Gate (978 tests)"
        status: "done"
        completed_at: "2026-02-24T00:00:00+09:00"
      - id: "F023"
        name: "sf-maker (Search First Maker) スキル"
        status: "done"
        completed_at: "2026-02-24T00:00:00+09:00"

  cautions:
    - id: "C009"
      category: "設計"
      content: "description内の技術キーワードを削りすぎないこと"
      reason: "装飾語だけではClaudeの発動判断が鈍るため、具体的トリガーフレーズの維持が必須"
