workflow:
  version: "2.0"
  last_updated: "2026-02-23T20:20:00+09:00"

  last_session_summary: |
    【Phase 15: ECC Skills Optimization & Integration】
    - 全44スキルの description 日本語化と「最強思想（Search First）」の注入を完遂。
    - ultra think を用いた精査により、description の発動精度と装飾語のバランスを最適化。
    - グローバル環境（`~/.claude/skills/`）への全スキル一括インストールを完了。
    - 実戦型マニュアル `ECC_PLAYBOOK.md` を作成し、`hello-claude` プロジェクトへ配布。
    - `hello-claude/CLAUDE.md` にスキルの活用意識と ECC 連携プロトコルを統合。

    【次にやること】
    - 新スキル環境での実走テスト
    - 各プロジェクト固有の専門スキルの抽出と構築
    - 並列開発（複数ターミナル）でのスキル干渉チェック

  progress:
    current_phase:
      number: 15
      name: "ECC Skills Optimization & Integration"
      status: "done"

    current_task:
      description: "セッション保存と知見の永続化"
      started_at: "2026-02-23T19:20:00+09:00"

    completed_phases:
      - phase: 10
        name: "Uber Data Pipeline 統合"
        completed_at: "2026-02-07"
      - phase: 11
        name: "Environment Migration & Optimization"
        completed_at: "2026-02-16"
      - phase: 12
        name: "System Kernel Refactoring (Persona Separation)"
        completed_at: "2026-02-17"
      - phase: 13
        name: "Master Agent Architecture Update"
        completed_at: "2026-02-23"
      - phase: 14
        name: "Establishment of Dual-Core Workflow"
        completed_at: "2026-02-23"

    next_tasks:
      - "新スキル環境での実走テスト"
      - "各プロジェクト固有の専門スキルの抽出と構築"

  decisions:
    adopted:
      - id: "D024"
        date: "2026-02-23"
        decision: "Claude Skills のグローバル全面展開 (ECC v2)"
        reason: "あらゆるプロジェクトで一貫したプロ品質の助言（最強思想）を自動発動させるため"
      - id: "D025"
        date: "2026-02-23"
        decision: "スキルトリガーの『思想×精度』両立方針"
        reason: "装飾語による思想注入と、技術用語による発動精度の両立がClaudeの能力最大化に不可欠なため"

  features:
    completed:
      - id: "F019"
        name: "ECC Strong Descriptions (44 skills)"
        status: "done"
        completed_at: "2026-02-23T20:10:00+09:00"
      - id: "F020"
        name: "ECC Global Installation"
        status: "done"
        completed_at: "2026-02-23T20:41:00+09:00"
      - id: "F021"
        name: "ECC Playbook & Hello-Claude Integration"
        status: "done"
        completed_at: "2026-02-23T20:17:00+09:00"

  cautions:
    - id: "C009"
      category: "設計"
      content: "description内の技術キーワードを削りすぎないこと"
      reason: "装飾語だけではClaudeの発動判断が鈍るため、具体的トリガーフレーズの維持が必須"
