workflow:
  version: "1.1.0"
  last_updated: "2026-02-10T11:25:00+09:00"

  last_session_summary: |
    【今回のセッションでやったこと】
    - 店舗詳細ページに横並びのタブナビゲーション（売り上げ, toreta, 食べログ等）を実装。✨🆕
    - タブの切り替え状態を管理し、コンテンツが切り替わる骨組み（Skeleton）を構築。
    - メインヘッダーとタブ部分を sticky (固定) にし、スクロール時の利便性を向上。
    
    【次にやること】
    - Phase 2: 各タブの具体的なコンテンツ実装。
    - まずは「売り上げ」タブの「売上・予約推移テーブル」の実装から着手。
    - 次に toreta データの詳細（予約経路等）を実装。

  progress:
    current_phase:
      number: 2
      name: "Toon 解析基盤の実装"
      status: "in_progress"
    
    current_task:
      description: "店舗詳細：各セクション（タブ）の実装"
      started_at: "2026-02-10"
    
    completed_phases:
      - phase: 1
        name: "環境構築 & ベースSkeleton実装"
        completed_at: "2026-02-10"

    next_tasks:
      - id: "T005"
        description: "店舗詳細：売上・予約推移テーブルの実装（売り上げタブ）"
      - id: "T006"
        description: "店舗詳細：月次推移グラフ（Recharts）の実装"
      - id: "T008"
        description: "店舗詳細：toreta/各媒体セクションのコンテンツ実装"

  decisions:
    adopted:
      - id: "D003"
        date: "2026-02-10"
        decision: "Tailwind v4 は Vite プラグイン (@tailwindcss/vite) で処理する"
        reason: "PostCSS 経由の直接呼び出しだと Vite v7 との相性でエラーが出るため"
      - id: "D004"
        date: "2026-02-10"
        decision: "日付ユーティリティ (formatYM) には必ず String キャストを含める"
        reason: "JSON/TOONのパース結果が数値として扱われ、substring 等が失敗するのを防ぐため"
      - id: "D005"
        date: "2026-02-10"
        decision: "sample/ フォルダの内容を設計の唯一の正解 (Source of Truth) とする"
        reason: "完成イメージとロジックが完璧に揃っているため、これをトレースするのが最短ルート"
      - id: "D006"
        date: "2026-02-10"
        decision: "メインコンテンツ最上部に大きな店舗名ヘッダーと期間バッジを表示する"
        reason: "ユーザーが常に「どの店舗のどの期間のデータ」を見ているかを一目で認識させるため"
      - id: "D007"
        date: "2026-02-10"
        decision: "すべてのReact Hooksは早期リターン(loading等)の前に定義する"
        reason: "Hooksの呼び出し順序が変化するとReactの内部状態が壊れ、致命的なランタイムエラーが発生するため"
      - id: "D008"
        date: "2026-02-10"
        decision: "店舗詳細に媒体別の横並びタブナビゲーションを設置する"
        reason: "情報量が多いダッシュボードで、ユーザーが表示したい情報を素早く切り替えられるようにするため"

  features:
    in_progress:
      - id: "F002"
        name: "店舗詳細レポート表示"
        status: "in_progress"
    
    planned:
      - id: "F003"
        name: "全店舗サマリー表示"
        status: "pending"

  file_structure:
    created:
      - "src/utils/toonParser.ts"
    to_create:
      - "src/components/ShopDetail.tsx"
      - "src/components/Summary.tsx"
    to_modify:
      - "src/App.tsx"

  cautions:
    - "toon.txt のデータは YYYYMM 形式だが、JS側で数値として認識される場合があるため型変換に注意。"
    - "Tailwind v4 の @import 構文は Vite プラグインがないと PostCSS でエラーになる。"
    - "タブ切り替え時のコンテンツ位置がズレないよう、sticky ヘッダーの高さを考慮する。"
