workflow:
  version: "1.1.0"
  last_updated: "2026-02-14T03:50:00+09:00"

  last_session_summary: |
    【今回のセッションでやったこと】
    - Recharts 100%積み上げ棒グラフによる予約経路構成比の可視化を実装。📊✨
    - グラフ詳細パネル（外部パネル）を実装し、ホバーに合わせてリアルタイムに詳細数値を表示。💅
    - テーブルの視認性爆上げ改修：gray-300境界線の強調、pr-12によるスクロールバーの完全分離。💎
    - 「Reserve Total」行を拡張し、全体に対するネット予約比率（%）を計算・表示するように変更。🚀
    ステータス:
  完了した機能:
    - "Universal Toon 解析エンジン"
    - "店舗ナビゲーションと選択"
    - "「売り上げ」タブ：税込計算およびウォークインの除外"
    - "店舗詳細：直近のプラン変更検出（過去6ヶ月分）"
    - "toretaタブ：構成比テーブルと100%積み上げ棒グラフの実装"
  未完了の機能:
    - "個別媒体セクション（食べログ・ホットペッパー等）の詳細コンテンツ"
    - "1ファイル構成によるHTMLエクスポート機能"
の検討。

  progress:
    current_phase:
      number: 2
      name: "店舗詳細の実装"
      status: "in_progress"
    
    current_task:
      description: "店舗詳細：各媒体セクションのコンテンツ実装"
      started_at: "2026-02-10"
    
    completed_phases:
      - phase: 1
        name: "環境構築 & ベースSkeleton実装"
        completed_at: "2026-02-10"
      - phase: 2-1
        name: "店舗詳細：売上・予約推移テーブル実装"
        completed_at: "2026-02-10"
      - phase: 2-2
        name: "店舗詳細：売上・予約推移テーブル改修（税込・YoY・プラン変更）"
        completed_at: "2026-02-14"
      - phase: 2-3
        name: "店舗詳細：toretaタブ 実装完了（構成比グラフ・詳細テーブル）"
        completed_at: "2026-02-14"

    next_tasks:
      - id: "T008"
        description: "店舗詳細：各媒体セクションのコンテンツ実装（食べログ等）"
      - id: "T009"
        description: "全店舗サマリー表示の実装"

  decisions:
    adopted:
      - id: "D003"
        date: "2026-02-10"
        decision: "Tailwind v4 は Vite プラグイン (@tailwindcss/vite) で処理する"
        reason: "PostCSS 経由の直接呼び出しだと Vite v7 との相性でエラーが出るため"
      - id: "D004"
        date: "2026-02-10"
        decision: "日付ユーティリティ (formatYM) には必ず String キャストを含める"
        reason: "JSON/TOONのパース結果が数値として扱われ、substring 等が失敗するのを防ぐため"
      - id: "D005"
        date: "2026-02-10"
        decision: "sample/ フォルダの内容を設計の唯一の正解 (Source of Truth) とする"
        reason: "完成イメージとロジックが完璧に揃っているため、これをトレースするのが最短ルート"
      - id: "D006"
        date: "2026-02-10"
        decision: "メインコンテンツ最上部に大きな店舗名ヘッダーと期間バッジを表示する"
        reason: "ユーザーが常に「どの店舗のどの期間のデータ」を見ているかを一目で認識させるため"
      - id: "D007"
        date: "2026-02-10"
        decision: "すべてのReact Hooksは早期リターン(loading等)の前に定義する"
        reason: "Hooksの呼び出し順序が変化するとReactの内部状態が壊れ、致命的なランタイムエラーが発生するため"
      - id: "D008"
        date: "2026-02-10"
        decision: "店舗詳細に媒体別の横並びタブナビゲーションを設置する"
        reason: "情報量が多いダッシュボードで、ユーザーが表示したい情報を素早く切り替えられるようにするため"
      - id: "D009"
      - id: "D010"
        date: "2026-02-14"
        decision: "構成比の分母はネット予約合計（合計 − ウォークイン）"
        reason: "sample.htmlの数値と一致。ネット予約の経路構成を見るのが目的"
      - id: "D011"
        date: "2026-02-14"
        decision: "ウォークイン行をテーブル内に表示（合計行の上、グレー背景）"
        reason: "ウォークイン比率も経営指標として重要。一画面で完結させる"
      - id: "D012"
        date: "2026-02-14"
        decision: "新規タブはTailwind CSSで実装、既存タブのインラインスタイルは触らない"
        reason: "スコープ・ロック遵守。新規コードから段階的にTailwind移行"
      - id: "D013"
        date: "2026-02-14"
        decision: "タブごとにデータ加工ユーティリティを分離（toretaBuilder.ts等）"
        reason: "タブ = ファイルの1対1対応で責務を明確化"
      - id: "D014"
        date: "2026-02-14"
        decision: "大規模テーブルのスクロールバー対策として pr-12 以上の特大パディングを確保"
        reason: "スクロールバー（インジケーター）がデータ数値と被るのを物理的に不可能にするため"
      - id: "D015"
        date: "2026-02-14"
        decision: "グラフ詳細は Recharts Tooltip を使わず、外部の専用 React コンポーネントに逃がす"
        reason: "狭いキャンバスにグラフを押し込めているため、Tooltip が画面外に消えたりグラフを隠したりするのを防ぐため"

  file_structure:
    created:
      - "src/utils/toonParser.ts"
      - "src/utils/toretaBuilder.ts"
    to_create:
      - "src/components/ShopDetail.tsx"
      - "src/components/Summary.tsx"
    to_modify:
      - "src/App.tsx"

  cautions:
    - "toon.txt のデータは YYYYMM 形式だが、JS側で数値として認識される場合があるため型変換に注意。"
    - "Tailwind v4 の @import 構文は Vite プラグインがないと PostCSS でエラーになる。"
    - "タブ切り替え時のコンテンツ位置がズレないよう、sticky ヘッダーの高さを考慮する。"
    - "ResponsiveContainer を使う際は親要素に必ず具体的な高さ (h-[320px] 等) が必要。"
