workflow:
  version: "1.5.0"
  last_updated: "2026-02-20T01:40:37+09:00"

  last_session_summary: |
    【コンソール警告修正・toretaタブ データ欠落バグ修正・ルール永続化 ✅】

    1. Recharts Tooltip の React.Fragment 警告を修正
       - content={<></>} を content={() => null} に変更
       - 対象: TabelogTab.tsx, HotpepperTab.tsx, GurunaviTab.tsx, App.tsx (4ファイル)

    2. toretaタブ 全店舗合計のデータ欠落バグを修正
       - 原因: toretaMedias 配列にハードコードされた媒体名が不足（電話・トレタ予約番・Retty・Googleで予約 が未集計）
       - 修正: 全店舗の toreta_data から動的に全媒体名を Set 収集する方式に変更
       - 効果: DB_toreta に新しい媒体が追加されても自動反映される

    3. Firebase構造・データフロー・toonParser整合性の全確認
       - GAS側 (firebasePusher.js, toonExporter.js) と new-world側 (App.tsx, toonParser.ts) の整合性OK

    4. GEMINI.md に ARCHITECTURE.yaml 更新ルールを永続化
       - 「動作確認と同時に ARCHITECTURE.yaml に記録する」ルールを追記

    5. ARCHITECTURE.yaml を更新（今回の変更を記録）

    【次にやること】
    - 個別店舗ビューでもtoretaタブの欠落媒体が表示されるか動作確認
    - 未実装の媒体タブ（Retty等）の詳細コンテンツ追加
    - 本番デプロイ時のCORS origin 追加

  status:
    完了した機能:
    - "Universal Toon 解析エンジン"
    - "Firebase 3系統データマージ (main, line, google)"
    - "「最新データに更新」トリガーボタン実装"
    - "LINE 公式アカウント分析タブ"
    - "Google ビジネスプロフィール分析タブ"
    - "店舗ナビゲーションと選択"
    - "「売り上げ」タブ：税込計算およびウォークインの除外"
    - "GAS -> Firebase 同期パイプライン（権限周りの修正完了）"
    - "Firebase Storage CORS 設定（localhost 5173/5174 の許可）✅"
    - "Recharts Tooltip React.Fragment 警告修正（4ファイル）✅"
    - "toretaタブ 全店舗合計：媒体名を動的収集方式に変更 ✅"
    未完了の機能:
    - "個別媒体セクション（Retty等）の詳細コンテンツ"
    - "1ファイル構成によるHTMLエクスポート機能"
    - "本番デプロイ時のCORS origin 追加"

  progress:
    current_phase:
      number: 4
      name: "運用基盤の安定化とUXポリッシュ"
      status: "in_progress"
    
    current_task:
      description: "toretaタブ動的収集化完了。次は個別店舗ビューの確認と未実装媒体タブの追加。"
      started_at: "2026-02-20T01:40:37+09:00"
    
    completed:
      - id: "T017"
        name: "App.tsx のJSX構造修復とレイアウト安定化"
        status: "done"
      - id: "T018"
        name: "GAS doPost パイプラインの権限エラー (OAuth) 修正"
        status: "done"
      - id: "T019"
        name: "Firebase Storage へのデータ書き出し正常確認"
        status: "done"
      - id: "T020"
        name: "Firebase Storage CORS 設定適用（localhost 5173/5174）"
        status: "done"
      - id: "T021"
        name: "Recharts Tooltip React.Fragment 警告修正（4ファイル）"
        status: "done"
      - id: "T022"
        name: "toretaタブ 全店舗合計の媒体名動的収集化"
        status: "done"

  decisions:
    adopted:
      - id: "D028"
        date: "2026-02-19"
        decision: "GASの appsscript.json に明示的な oauthScopes を追加する"
        reason: "トリガー実行時に暗黙的な権限では UrlFetchApp や ScriptApp が失敗するため、確実な認可が必要。"
      - id: "D029"
        date: "2026-02-19"
        decision: "手動認証用の authCheck 関数を GAS に常備する"
        reason: "Webアプリの更新だけでは新しい権限が付与されないケースがあるため、エディタから手動実行で承認ポップアップを強制させる。"
      - id: "D030"
        date: "2026-02-19"
        decision: "App.tsx のメインコンテンツには必ずデータの存在チェック（guards）を配置する"
        reason: "初回同期前などのデータが null の状態で子要素がマウントされ、レンダリングエラーで画面が白くなるのを防ぐため。"
      - id: "D031"
        date: "2026-02-20"
        decision: "Firebase Storage の CORS 設定に localhost:5173 と localhost:5174 の両方を含める"
        reason: "Vite の dev server はポートが使用中の場合に +1 したポートにフォールバックするため、両方許可しておく必要がある。"
      - id: "D032"
        date: "2026-02-20"
        decision: "Recharts の Tooltip を非表示にする場合は content={() => null} を使用する"
        reason: "content={<></>}（React.Fragment）は Recharts が内部で props を注入しようとして Invalid prop 警告が発生するため。"
      - id: "D033"
        date: "2026-02-20"
        decision: "全店舗合計のtoreta集計は、各店舗のtoreta_dataから動的にSetで全媒体名を収集する"
        reason: "ハードコードしたリストでは DB_toreta に追加された媒体が反映されず、欠落バグが生まれるため。"

  file_structure:
    created:
      - "src/utils/toonParser.ts"
      - "src/utils/toretaBuilder.ts"
      - "src/components/TabelogTab.tsx"
      - "src/components/HotpepperTab.tsx"
      - "src/components/GurunaviTab.tsx"
      - "src/components/LineTab.tsx"
      - "src/components/GoogleTab.tsx"
      - "cors.json"
    modified:
      - "src/App.tsx（toreta動的収集化・Tooltip修正）"
      - "src/components/TabelogTab.tsx（Tooltip修正）"
      - "src/components/HotpepperTab.tsx（Tooltip修正）"
      - "src/components/GurunaviTab.tsx（Tooltip修正）"
      - "../report-renewal/s-tock/main.js"
      - "../report-renewal/s-tock/firebasePusher.js"
      - "../report-renewal/s-tock/appsscript.json"
      - "prompt/ARCHITECTURE.yaml（変更記録を追記）"
      - "/Users/matsumotohiroki/.gemini/GEMINI.md（ARCHITECTURE更新ルール永続化）"

  cautions:
    - "GAS の新規デプロイ時は、新しいスコープが含まれているか確認し、「アクセスを承認」フローを必ず通すこと。"
    - "JSXのネスト（特に三項演算子のチェーン）は可読性が落ちやすく壊れやすいため、将来的にタブコンポーネントの切り出しを検討。"
    - "本番デプロイ時は cors.json の origin を本番 URL (https://...) に更新して再適用すること。"
    - "Firebase Storage の CORS 設定は gsutil または Cloud Shell で管理。ローカルに Google Cloud SDK が必要。"
    - "toretaタブの個別店舗ビューで欠落媒体がゼロ/空欄の場合、DB_toretaにその媒体のデータ行が存在しない可能性がある（データ側の問題）。"
