workflow:
  version: "1.0.0"
  last_updated: "2026-02-26 23:10"

  last_session_summary: |
    【今回のセッションで話したこと・決まったこと】
    - 新プロジェクト `ftp-pos-sync` の立ち上げと「調査ファースト」方針の決定。
    - 調査用スクリプト `src/ftp_sample.py` の実行により、仕様書（LZH）と実態（ZIP）の乖離を発見。
    - FTPサーバーの挨拶メッセージやファイル名が Shift-JIS (cp932) であることを特定し、エラーを解消。
    - ZIP内のファイル構成（7つのCSV：ITEM, NIKKEI等）とデータ構造（1行目メタ、2行目ヘッダー）を確認。
    - FTPサーバーが一度に1000件しか表示しない制限があることを確認。

    【今後の方向性・これから決めること】
    - 7つのCSVのうち、どのデータをスプレッドシートのどのシートへ書き込むかを確定する。
    - 2nd Phase (本実装) として、パースからスプレッドシート書き込み、FTP上のデータ削除までの自動化を実装する。

    【次にやること（実行順序）】
    1. ひろきくんから「書き込み対象のCSVファイルと項目」の指示をもらう（ITEMかNIKKEIか、あるいは両方か）。
    2. 書き込み先スプレッドシートの準備（URL、認証用サービスアカウント等）。
    3. 2nd Phase の詳細ヒアリング（既存データへの追記か上書きか等）。
    4. 本番用自動化モジュールの設計（ftp_client.py, parser.py, spreadsheet.py）。

  progress:
    current_phase:
      number: 1
      name: "1st Phase: 調査・データ把握"
      status: "in_progress"
    
    current_task:
      description: "スプレッドシート書き込み対象データの確定待ち"
      started_at: "2026-02-26 22:45"
    
    completed_phases:
      - phase: 0
        name: "プロジェクト立ち上げ・要件定義"
        completed_at: "2026-02-26"
    
    next_tasks:
      - "スプレッドシート連携仕様のヒアリング (2nd Phase開始)"
      - "Google Sheets API 認証情報の準備"
      - "自動化用モジュールの実装"

  decisions:
    adopted:
      - id: "D001"
        date: "2026-02-26"
        decision: "調査ファースト・分断プロトコルの採用"
        reason: "実データの中身が不明なまま本実装すると手戻りが大きいため。"
      - id: "D003"
        date: "2026-02-26"
        decision: "文字コードを cp932 に固定"
        reason: "UTF-8では接続メッセージのデコードで例外が発生したため。"
      - id: "D004"
        date: "2026-02-26"
        decision: "解凍処理はZIP形式（unzip等）で実装"
        reason: "拡張子はTXTだが、バイナリヘッダー(PK)によりZIPであることが確定したため。"

  features:
    completed:
      - id: "F001"
        name: "FTPサンプル取得・形式判定（実物調査）"
        status: "done"
    in_progress: []
    planned:
      - id: "F002"
        name: "FTP自動取得・差分ダウンロード"
        status: "planned"
      - id: "F003"
        name: "POSデータパース（複数CSV対応）"
        status: "planned"
      - id: "F004"
        name: "スプレッドシート自動書き込み"
        status: "planned"
      - id: "F005"
        name: "FTP元データ自動削除"
        status: "planned"

  file_structure:
    created:
      - "prompt/PROJECT_SPECIFIC.yaml"
      - "prompt/WORKFLOW.yaml"
      - "src/ftp_sample.py"
      - ".env.example"
    to_create:
      - "src/ftp_client.py"
      - "src/extractor.py"
      - "src/parser.py"
      - "src/spreadsheet_updater.py"
