workflow:
  version: "1.2.0"
  last_updated: "2026-02-27 15:25:00"

  last_session_summary: |
    【今回のセッションで話したこと・決まったこと】
    - 転記.gsの実行前チェック：`.clear()` で毎回全消しになっている問題を発見。
    - ひろきくんの運用方針の確認：生データ（Sheet1）は膨大になる（10万行/月）ため毎月上書きし、集計データ（商品出数管理、曜日・時間帯別傾向）は月をまたいで蓄積（溜め込み）していく方針を決定。
    - 複合キーのリスクヘッジ：曜・時間帯別傾向シートで、レシートNoが月ごとにリセットされる可能性を考慮し、複合キーに「年月」を追加。
    - ダッシュボード構築の要件ヒアリング：時間帯別売上、曜日別売上、フード・ドリンク比率、コース売上比率、カテゴリ別商品ランキングを1つのHTMLページで表示する機能要件を整理。
    - データの実地調査：ブラウザ・ツールを使用して実データの部門名称、分類名称、時間帯フォーマットを確認。コースや飲み放題が分類名称に含まれる事実を特定。

    【今後の方向性・これから決めること】
    - データ構造とロジックを優先した、GAS doGet で動くHTML版ダッシュボードを早期実装し、実データでの集計精度を検証する。
    - pos_accumulator.py の対象月ハードコード（202602）の動的化。
    - コース判定や商品ランキングにおける除外/包含条件の細部詰め。

    【次にやること（実行順序）】
    1. 修正・Upsert化した `gas/転記.gs` をGASへコピペデプロイ。
    2. 既存店舗への「業態」初期値入力（手動）を完了させる。
    3. `prompt/plan.md` に基づき、`gas/dashboard.gs` と `gas/dashboard.html` の実装を開始。
    4. 実データを流し込み、ダッシュボードの表示と集計数値を既存の集計シートと照らし合わせて検証。

  progress:
    current_phase:
      number: 2
      name: "2nd Phase: 転記・集計基盤の構築とマスタ連携"
      status: "in_progress"
    
    current_task:
      description: "集計シートのUpsert化完了とダッシュボード実装プラン策定"
      started_at: "2026-02-27 09:00"
    
    completed_phases:
      - phase: 0
        name: "プロジェクト立ち上げ・要件定義"
        completed_at: "2026-02-26"
      - phase: 1
        name: "1st Phase: 調査・データ把握"
        completed_at: "2026-02-26"
    
    next_tasks:
      - "Upsert型 転記.gs のGASへのコピペ反映"
      - "plan.md に基づくダッシュボード機能（GS/HTML）の実装"
      - "pos_accumulator.py による最新データ投入とダッシュボード表示確認"
      - "FTP上のデータ自動削除の有効化（本番運用開始時）"

  decisions:
    adopted:
      - id: "D007"
        date: "2026-02-26"
        decision: "Pythonによるローカル監査（audit_menu_codes.py）の実施"
        reason: "GASの6分制限のため、10万行を超えるPOSデータの全件重複監査がタイムアウトしたため、Python側から直接FTPを叩いて高速監査を行った。"
      - id: "D008"
        date: "2026-02-26"
        decision: "商品出数管理の集計キーを「業態＋店舗CD＋ﾒﾆｭｰCD＋年月」とする"
        reason: "CDの重複登録やメニュー名のゆれがあるため、店舗CDとCDの完全一致、かつ月別のトレンドを追えるようにする必要があったため。"
      - id: "D009"
        date: "2026-02-27"
        decision: "業態マスタは report-renewal 側の shops シートで一元管理"
        reason: "データの二重管理を防ぎ、かつUI（master.html）を使い回すため。"
      - id: "D010"
        date: "2026-02-27"
        decision: "master.html 内の業態入力の選択式（ドロップダウン）化"
        reason: "テキストの自由入力による「アジアン」「Asian」などの表記ゆれによって集計が分散するのを防ぐため。"
      - id: "D011"
        date: "2026-02-27"
        decision: "集計シートをUpsert方式（既存保持・重複上書き）に変更"
        reason: "生データが10万行/月と肥大するためSheet1を毎月上書き運用とするが、集計累計結果は月をまたいで蓄積させたいため。"
      - id: "D012"
        date: "2026-02-27"
        decision: "曜日・時間帯別傾向の複合キーに「年月」を追加"
        reason: "レシートNoが店舗ごとに月単位でリセットされる可能性を考慮し、異なる月で同一キーが衝突（上書き）されるのを防ぐため。"

  features:
    in_progress:
      - id: "F003"
        name: "POSデータパースと巨大データの処理"
        status: "in_progress"
      - id: "F004"
        name: "スプレッドシート自動転記＆高度な集計分析"
        status: "in_progress"
      - id: "F007"
        name: "POS分析ダッシュボード（HTML版）の構築"
        status: "in_progress"
    planned:
      - id: "F005"
        name: "FTP元データ自動削除"
        status: "planned"
    completed:
      - id: "F001"
        name: "FTPサンプル取得・形式判定（実物調査）"
      - id: "F002"
        name: "FTP自動取得・差分ダウンロード"
      - id: "F006"
        name: "マスターUIへの業態プルダウンの追加（report-renewal側）"

  file_structure:
    created:
      - "prompt/plan.md"
      - "prompt/ARCHITECTURE.yaml"
    to_create:
      - "gas/dashboard.gs"
      - "gas/dashboard.html"
    to_modify:
      - "gas/転記.gs"

  cautions:
    - "GASで別スプレッドシート（マスター）を参照するため、SpreadsheetApp.openById() の初回実行時に権限の承認ポップアップ許可が必須。"
    - "集計シートは現在 Upsert ロジック上、毎回全行読み込んで上書きするため、行数が数万件を超えるとGAS上でのメモリ制限や時間制限を考慮する必要が出てくる可能性がある。"
