workflow:
  last_updated: "2026-02-15"
  
  last_session_summary: |
    【今回のセッションでやったこと】
    - プロジェクト「Word-Bank」の作成開始
    - 要件定義と仕様策定完了
    - プロジェクトフォルダと初期ファイルの作成（prompt/）
    
    【次にやること】
    - 環境構築（Firebase設定、Tailwind設定）
    - 実装フェーズ開始（Cycle 1: 基盤構築）
  
  progress:
    current_phase:
      number: 1
      name: "環境構築"
      status: "in_progress"
    
    completed_phases: []
  
  decisions:
    adopted:
      - id: "D001"
        decision: "技術スタック: React + Tailwind + Firebase + Vercel"
        reason: "個人開発における開発速度と保守性を最大化するため"
      - id: "D002"
        decision: "UIデザイン: Claudeカラーパレットを採用"
        reason: "モダンで落ち着いた、作業に集中できる配色のため"
      - id: "D003"
        decision: "ディレクトリ構造: prompt/ でプロジェクト管理を行う"
        reason: "GA-Workspace標準に準拠し、エージェントとの協業効率を高めるため"
  
  features:
    completed: []
    in_progress: []
    planned:
      - id: "F001"
        name: "Google認証機能"
        status: "todo"
      - id: "F002"
        name: "メインレイアウト実装"
        status: "todo"
      - id: "F003"
        name: "カテゴリ管理機能"
        status: "todo"
      - id: "F004"
        name: "プロンプトCRUD機能"
        status: "todo"
      - id: "F005"
        name: "検索機能"
        status: "todo"
      - id: "F006"
        name: "タブ機能"
        status: "todo"

  cautions:
    - "権限エラー回避のため、ディレクトリ作成やファイル操作には注意が必要。コマンド実行は慎重に。"
