workflow:
  version: "1.1"
  last_updated: "2026-02-12T17:30:00+09:00"

  last_session_summary: |
    【今回のセッションでやったこと】
    - T020 完全クリア！🎉✨ update_drink_item を b-log 完全再現版に修正！
    - T021 完全成功！🎉✨ カテゴリー行追加処理を実装！
    - カテゴリー設定で visible な行数を確認し、足りなければ自動で追加する処理を実装
    - 本番データで完全成功！15カテゴリー、74商品、全て登録成功！💪
    - Streamlit UI 完成！ワークフロー選択、店舗選択（19店舗）、拡張可能な設計
    - Phase 2 完了！ドリンクメニュー一括更新フロー、完全稼働！🏆✨
    
    【次にやること】
    - Phase 3: 実運用・改善フェーズ
    - 他のワークフロー（コースメニュー、料理メニュー等）の追加

  progress:
    current_phase:
      number: 3
      name: "実運用・改善"
      status: "ready"
    
    current_task:
      description: "実運用開始"
      started_at: "2026-02-12T17:30:00"
    
    completed_phases:
      - phase: 0
        name: "要件定義"
        completed_at: "2026-02-10"
      - phase: 1
        name: "管理体制の構築 & 構造化"
        completed_at: "2026-02-10"
      - phase: 2
        name: "主要 Skill 実装 & 動作確認"
        completed_at: "2026-02-12T17:30:00"

    tasks:
      - id: "T014"
        description: "Drinkメニュー用 Skill 動作確認（第二幕：見出し再構築のみ）"
        status: "done"
      - id: "T015"
        description: "Drinkメニュー用 Skill 動作確認完了（第三幕：実商品の登録）および Flow 実装"
        status: "done"
      - id: "T017"
        description: "T015 Act 3 本編：一括更新 Flow の実戦投入テスト（原子テスト版）"
        status: "done"
        completed_at: "2026-02-12T01:10:00"
        note: "ログインから保存完了、そして編集画面への正確な帰還までを最小データセットでクリア！💅✨"
      - id: "T018"
        description: "T015 Act 3 最終確認：複数データセットによるスケールテスト（ひろきくん式実装完了）"
        status: "done"
        completed_at: "2026-02-12T15:44:00"
        note: "ひろきくん式（カウント→一括追加→上から順番に埋める）実装完了。行追加成功、残りは入力ロジック修正のみ。💍✨"
      - id: "T020"
        description: "update_drink_item の入力ロジック修正（b-log完全再現版）"
        status: "done"
        completed_at: "2026-02-12T16:45:00"
        note: "b-logに基づいて直接ID指定に変更。ドット回避も実装。全体フローも成功！💖✨"
      - id: "T021"
        description: "カテゴリー行追加処理 & 本番データ完全成功"
        status: "done"
        completed_at: "2026-02-12T17:30:00"
        note: "カテゴリー15個、商品74件、全て成功！Streamlit UI も完成。Phase 2 完了！🏆✨"

  decisions:
    adopted:
      - id: "D012"
        date: "2026-02-12"
        decision: "保存完了画面からの帰還に「行特定＋編集ボタン」方式を採用"
        reason: "他カテゴリ（コース、料理等）の編集ボタンへの誤爆を防ぎ、確実にドリンク編集画面に戻るため"
      - id: "D013"
        date: "2026-02-12"
        decision: "削除対象を tr[id^='drinkMenu'] に限定"
        reason: "ホットペッパーの仕様上、おすすめやこだわりを巻き添えにしないため。BOOK.mdに禁忌として記録。"
      - id: "D014"
        date: "2026-02-12"
        decision: "プラン提示前の実装禁止（ガバナンス強化）"
        reason: "自律判断の暴走を防ぎ、ユーザーとの合意に基づいた確実な開発を進めるため。DEVELOPMENT_FLOW.mdに絶対の掟として追加。"
      - id: "D015"
        date: "2026-02-12"
        decision: "永続的記憶（Persistent Memory）の掟の導入"
        reason: "ユーザーの指示をその場限りにせず、必ずドキュメント化して次セッションに繋げるため。00-definition.mdに追加。"
      - id: "D016"
        date: "2026-02-12"
        decision: "/fact-check ワークフローの導入と必須化"
        reason: "作業前のプランニングフェーズで仕様理解を一問一答形式で確認し、誤解や推測による実装ミスを物理的に防ぐため。"
      - id: "D017"
        date: "2026-02-12"
        decision: "サンプルデータの反映方法は引数渡しを採用"
        reason: "柔軟性を確保し、毎回違うデータでテストできるようにするため。"
      - id: "D018"
        date: "2026-02-12"
        decision: "ひろきくん式の実装（カウント→一括追加→上から順番に埋める）"
        reason: "既存行数を正確に把握し、必要な分だけ追加してから全体の通し番号で入力する方が確実で効率的なため。"
      - id: "D019"
        date: "2026-02-12"
        decision: "update_drink_item を b-log 完全再現版に変更（直接ID指定）"
        reason: "複雑な行特定ロジック（tr:has()）がタイムアウトの原因。b-logで確認した通り、直接#drinkName{index}で指定する方が確実。"
      - id: "D020"
        date: "2026-02-12"
        decision: "Flowでも既存indexを取得して実際のindexに合わせて入力"
        reason: "index 0 は存在しない。既存の行（index 1, 2, 3...）を取得して、それに合わせて入力する必要がある。"

  file_structure:
    created:
      - path: "hotpepper/skill/data_parser.py"
        description: "テキスト形式のメニューデータを構造化データに変換するパーサー。BOOK.md 仕様に完全準拠。"
      - path: ".agent/workflows/fact-check.md"
        description: "作業前の仕様理解確認ワークフロー（グローバル）。一問一答形式、3案+おすすめ提示、即時永久保存。"
      - path: "tests/test_t020_blog_simple.py"
        description: "b-log完全再現テスト。直接ID指定の動作確認。"
      - path: "tests/test_t020_real_data.py"
        description: "本番データ（data_parser）との連携テスト。"
      - path: "tests/test_t020_flow_complete.py"
        description: "全体フロー（process_drink_menu）のテスト。"
    modified:
      - path: "hotpepper/skill/drink_ops.py"
        description: "update_drink_item を b-log 完全再現版に変更。直接ID指定、ドット回避のラジオボタンロジック追加。"
      - path: "hotpepper/flow/drink_update.py"
        description: "既存indexを取得して実際のindexに合わせて入力する方式に変更。index 0 決め打ちを廃止。"
      - path: "BOOK.md"
        description: "データフォーマット仕様を超詳細に追記（見出し=カテゴリ、説明文不要、価格判定ロジック等）。"
      - path: "prompt/KNOWLEDGE.md"
        description: "セッション19-20の知見として、RPA における媒体固有仕様の即時記録、ひろきくん式実装を追加。"
      - path: ".agent/workflows/resume-session.md"
        description: "/fact-check を Step 8 として追加。"
      - path: ".agent/workflows/start-project.md"
        description: "/fact-check を Step 2.5 として追加。"
      - path: ".agent/workflows/workflow-templates.md"
        description: "新規開発・修正改善の初期フェーズに /fact-check を組み込み。"
      - path: ".agent/workflows/sf-maker.md"
        description: "Phase 1.5 として /fact-check を追加。フェーズ遷移ルールも更新。"

  cautions:
    - "ホットペッパーの削除は tr[id^='drinkMenu'] 以外を触らないこと！"
    - "保存完了画面では「ドリンク」行の編集ボタンを狙い撃つこと！"
    - "修正前は必ずプランを提示し、GOサインをもらうこと！💅🛡️"
    - "仕様説明を受けた瞬間、「後で書く」は禁止。その場で BOOK.md or KNOWLEDGE.md に刻むこと！💍"
    - "作業前のプランニングフェーズでは必ず /fact-check を実施し、仕様理解を100%確定させること！🔍✨"
    - "既存の動作していたファイルを確認せずに新規作成しない！必ず既存パターンを踏襲すること！⚠️"
    - "update_drink_item: 次回は test_experiment_register_drinks.py から入力ロジックを確実に引き継ぐ！💪"
