workflow:
  version: "1.3"
  last_updated: "2026-02-13T15:20:00+09:00"

  last_session_summary: |
    【今回のセッションでやったこと】
    - プロジェクト全体の大規模リファクタリング (T024) 完了！
    - テストファイルの整理 (Phase 1)
    - スキルの切り出しと集約 (Phase 2)
    - Flow と Skill の分離 (Phase 3)
    - App のビジネスロジック排除 (Phase 4)
    - テストライフサイクル管理の導入 (Phase 5)
    - RPA.app のパス問題を解決し再構築
    
    【今回のセッションでやったこと】
    - ドリンクメニューのカテゴリー/インデックス不一致問題を解決。カテゴリーごとのテーブル内でのインデックス抽出ロジック（Isolated Indexing）を実装。
    - 価格入力時の `Locator.click: Timeout` エラーを解決。b-log データを元に、入力前に適切なラジオボタン（数値価格 vs 標準）を自動選択するロジックを実装。
    - インデックス解析ツール `inspect_drink_indices.py` を作成し、画面上の実数値を可視化。
    - ユーザールール（カテゴリー0無視、1から対象）の徹底遵守。
    
    【次にやること】
    - 他メニュー（コース、料理等）へのカテゴリー別インデックス方式の横展開。
    - 実運用データのさらなる投入テスト。

  progress:
    current_phase:
      number: 3
      name: "実運用・改善"
      status: "in_progress"
    
    current_task:
      description: "カテゴリー別インデックス方式の安定稼働確認"
      started_at: "2026-02-13T17:30:00"
    
    completed_phases:
      - phase: 0
        name: "要件定義"
        completed_at: "2026-02-10"
      - phase: 1
        name: "管理体制の構築 & 構造化"
        completed_at: "2026-02-10"
      - phase: 2
        name: "主要 Skill 実装 & 動作確認"
        completed_at: "2026-02-12T17:30:00"
      - phase: 3 # リファクタリング完了フェーズとして扱う
        name: "構造改革 (Refactoring)"
        completed_at: "2026-02-13T15:20:00"

    tasks:
      - id: "T014"
        description: "Drinkメニュー用 Skill 動作確認（第二幕：見出し再構築のみ）"
        status: "done"
        test_files:
          - "tests/test_blog_perfect.py"
          - "tests/test_drink_skills.py"
        cleaned: true
      - id: "T015"
        description: "Drinkメニュー用 Skill 動作確認完了（第三幕：実商品の登録）および Flow 実装"
        status: "done"
        test_files:
          - "tests/test_drink_skills.py"
          - "tests/test_flow_register_drinks.py"
        cleaned: true
      - id: "T017"
        description: "T015 Act 3 本編：一括更新 Flow の実戦投入テスト（原子テスト版）"
        status: "done"
        completed_at: "2026-02-12T01:10:00"
        note: "ログインから保存完了、そして編集画面への正確な帰還までを最小データセットでクリア！💅✨"
        test_files:
          - "tests/test_flow_register_drinks.py"
        cleaned: true
      - id: "T018"
        description: "T015 Act 3 最終確認：複数データセットによるスケールテスト（ひろきくん式実装完了）"
        status: "done"
        completed_at: "2026-02-12T15:44:00"
        note: "ひろきくん式（カウント→一括追加→上から順番に埋める）実装完了。行追加成功、残りは入力ロジック修正のみ。💍✨"
        test_files:
          - "tests/test_t018_scale_test.py"
        cleaned: true
      - id: "T020"
        description: "update_drink_item の入力ロジック修正（b-log完全再現版）"
        status: "done"
        completed_at: "2026-02-12T16:45:00"
        note: "b-logに基づいて直接ID指定に変更。ドット回避も実装。全体フローも成功！💖✨"
        test_files:
          - "tests/test_t020_blog_simple.py"
          - "tests/test_t020_flow_complete.py"
          - "tests/test_t020_real_data.py"
          - "tests/test_t020_simple_input.py"
        cleaned: true
      - id: "T021"
        description: "カテゴリー行追加処理 & 本番データ完全成功"
        status: "done"
        completed_at: "2026-02-12T17:30:00"
        note: "カテゴリー15個、商品74件、全て成功！Streamlit UI も完成。Phase 2 完了！🏆✨"
        cleaned: true
      - id: "T022"
        description: "税込チェックボックス対応（with_tax）"
        status: "done"
        completed_at: "2026-02-12T20:25:00"
        note: "b-logの生データからセレクタを特定し、推測なしで完全実装。1-indexedの罠（index 0アクセス）も修正完了！💪💎"
        test_files:
          - "tests/test_t020_blog_simple.py"
          - "tests/test_t020_simple_input.py"
        cleaned: true
      - id: "T023_UI"
        description: "デスクトップ起動アプリ (RinaRPA.app) 作成"
        status: "done"
        completed_at: "2026-02-13T09:45:00"
        note: "Python経由起動でPATH問題を解決し、osacompileでネイティブアプリ化。ワンクリック起動を実現！🚀"
        cleaned: true
      - id: "T024_REFACTOR"
        description: "プロジェクト完全リファクタリング (構造改革)"
        status: "done"
        completed_at: "2026-02-13T15:20:00"
        note: "スキル/フロー分離、テスト整理、ドキュメント同期を完遂。App起動問題も解決。"
        cleaned: true
      - id: "T025_INDEX_FIX"
        description: "カテゴリー/インデックス不一致問題の根本解決"
        status: "done"
        completed_at: "2026-02-13T17:35:00"
        note: "カテゴリーごとのテーブル内アイソレーションを実装。インデックス解析ツール完備。💅💎"
        cleaned: true
      - id: "T026_RADIO_FIX"
        description: "価格入力時の disabled 解除（ラジオボタン自動選択）"
        status: "done"
        completed_at: "2026-02-13T17:35:00"
        note: "b-logに基づき、数値価格(0)と標準(1)を適切に切り替え。Timeoutエラーを根絶！✨"
        cleaned: true

  decisions:
    adopted:
      - id: "D012"
        date: "2026-02-12"
        decision: "保存完了画面からの帰還に「行特定＋編集ボタン」方式を採用"
        reason: "他カテゴリ（コース、料理等）の編集ボタンへの誤爆を防ぎ、確実にドリンク編集画面に戻るため"
      - id: "D013"
        date: "2026-02-12"
        decision: "削除対象を tr[id^='drinkMenu'] に限定"
        reason: "ホットペッパーの仕様上、おすすめやこだわりを巻き添えにしないため。BOOK.mdに禁忌として記録。"
      - id: "D014"
        date: "2026-02-12"
        decision: "プラン提示前の実装禁止（ガバナンス強化）"
        reason: "自律判断の暴走を防ぎ、ユーザーとの合意に基づいた確実な開発を進めるため。DEVELOPMENT_FLOW.mdに絶対の掟として追加。"
      - id: "D015"
        date: "2026-02-12"
        decision: "永続的記憶（Persistent Memory）の掟の導入"
        reason: "ユーザーの指示をその場限りにせず、必ずドキュメント化して次セッションに繋げるため。00-definition.mdに追加。"
      - id: "D016"
        date: "2026-02-12"
        decision: "/fact-check ワークフローの導入と必須化"
        reason: "作業前のプランニングフェーズで仕様理解を一問一答形式で確認し、誤解や推測による実装ミスを物理的に防ぐため。"
      - id: "D017"
        date: "2026-02-12"
        decision: "サンプルデータの反映方法は引数渡しを採用"
        reason: "柔軟性を確保し、毎回違うデータでテストできるようにするため。"
      - id: "D018"
        date: "2026-02-12"
        decision: "ひろきくん式の実装（カウント→一括追加→上から順番に埋める）"
        reason: "既存行数を正確に把握し、必要な分だけ追加してから全体の通し番号で入力する方が確実で効率的なため。"
      - id: "D019"
        date: "2026-02-12"
        decision: "update_drink_item を b-log 完全再現版に変更（直接ID指定）"
        reason: "複雑な行特定ロジック（tr:has()）がタイムアウトの原因。b-logで確認した通り、直接#drinkName{index}で指定する方が確実。"
      - id: "D020"
        date: "2026-02-12"
        decision: "Flowでも既存indexを取得して実際のindexに合わせて入力"
        reason: "index 0 は存在しない。既存の行（index 1, 2, 3...）を取得して、それに合わせて入力する必要がある。"
      - id: "D021"
        date: "2026-02-13"
        decision: "ui_app.py → app.py リネーム"
        reason: "エントリーポイントの命名を標準化。"
      - id: "D022"
        date: "2026-02-13"
        decision: "ルート直下の不要ファイル全削除"
        reason: "プロジェクト構造のクリーン化。"
      - id: "D023"
        date: "2026-02-13"
        decision: "run.py 削除、GUI化時に再構築"
        reason: "古い実装を排除し、app.py に統合するため。"
      - id: "D024"
        date: "2026-02-13"
        decision: "flow内スキル未分離ロジックの切り出し必須化"
        reason: "ワークフロー内にスキルを埋め込むことは技術的負債となるため。"
      - id: "D025"
        date: "2026-02-13"
        decision: "course_update.py のリファクタはコースGUI化時に実施"
        reason: "今回は影響範囲を限定するため。"
      - id: "D026"
        date: "2026-02-13"
        decision: "テスト命名規則 test_{タスクID}_{内容}.py 必須化"
        reason: "テストファイルの目的とライフサイクルを明確にするため。"
      - id: "D027"
        date: "2026-02-13"
        decision: "WORKFLOW.yaml にテストトラッキング欄を追加"
        reason: "テストファイルの削除漏れを防ぎ、クリーンな状態を維持するため。"
      - id: "D028"
        date: "2026-02-13"
        decision: "browser.py でブラウザセッション管理を共通スキル化"
        reason: "全ワークフロー共通のブラウザ起動処理を集約するため。"
      - id: "D029"
        date: "2026-02-13"
        decision: "各flowに run() を追加、app.py はflow指定+引数渡しのみ"
        reason: "app.py をUI定義に専念させ、ワークフロー追加を容易にするため。"
      - id: "D030"
        date: "2026-02-13"
        decision: "rpaの基本.txt 削除"
        reason: "BOOK.md/KNOWLEDGE.md に統合済みのため。"
      - id: "D031"
        date: "2026-02-13"
        decision: "prompt/ 整理（SESSION_STATE.yaml, BOOK.yaml 削除）"
        reason: "未使用ファイルを削除し、混乱を防ぐため。"
      - id: "D032"
        date: "2026-02-13"
        decision: "start_ui.command を python3 -m streamlit で実行するように変更"
        reason: "Desktop App起動時のPATH環境変数問題を回避するため。"
      - id: "D033"
        date: "2026-02-13"
        decision: "カテゴリー別インデックス・アイソレーション方式の採用"
        reason: "ページ全体からインデックスを取ると、カテゴリーの境界でズレが生じるため。各テーブル内を独立してスキャンするのが最も確実。"
      - id: "D034"
        date: "2026-02-13"
        decision: "価格入力前のラジオボタン自動選択"
        reason: "ホットペッパーの仕様上、適切なラジオボタンを選択しないと入力欄が disabled になり Timeout するため。"

  file_structure:
    created:
      - path: "hotpepper/skill/browser.py"
        description: "全ワークフロー共通のブラウザセッション管理スキル。"
      - path: "hotpepper/skill/data_parser.py"
        description: "テキスト形式のメニューデータを構造化データに変換するパーサー。"
      - path: ".agent/workflows/fact-check.md"
        description: "作業前の仕様理解確認ワークフロー（グローバル）。"
    modified:
      - path: "hotpepper/skill/drink_ops.py"
        description: "スキル切り出しによる拡張。"
      - path: "hotpepper/flow/drink_update.py"
        description: "スキル分離と run() 関数追加によるリファクタリング。"
      - path: "app.py"
        description: "旧 ui_app.py。ビジネスロジックを排除し、動的インポートに対応。"
      - path: "prompt/WORKFLOW.yaml"
        description: "テストトラッキング機能の追加、タスク・決定事項の更新。"
      - path: "start_ui.command"
        description: "PATH問題に対応した堅牢な起動スクリプトに更新。"

  cautions:
    - "ホットペッパーの削除は tr[id^='drinkMenu'] 以外を触らないこと！"
    - "保存完了画面では「ドリンク」行の編集ボタンを狙い撃つこと！"
    - "修正前は必ずプランを提示し、GOサインをもらうこと！💅🛡️"
    - "仕様説明を受けた瞬間、「後で書く」は禁止。その場で BOOK.md or KNOWLEDGE.md に刻むこと！💍"
    - "作業前のプランニングフェーズでは必ず /fact-check を実施し、仕様理解を100%確定させること！🔍✨"
    - "既存の動作していたファイルを確認せずに新規作成しない！必ず既存パターンを踏襲すること！⚠️"
    - "update_drink_item: 次回は test_experiment_register_drinks.py から入力ロジックを確実に引き継ぐ！💪"
    - "テストファイルは必ず test_{タスクID}_{内容}.py の命名規則に従うこと！"
    - "タスクがdoneになったら、test_filesフィールドに対応テストを記録し、削除後にcleaned: trueにすること！"
    - "セッション開始時に done かつ cleaned: false のタスクが残っていないか確認すること！"
