workflow:
  version: "1.1"
  last_updated: "2026-02-12T15:44:00+09:00"

  last_session_summary: |
    【今回のセッションでやったこと】
    - T018 完全実装！ひろきくん式（カウント→一括追加→上から順番に埋める）を実現！🎉✨
    - count_rows_per_category: 追加ボタンの親テーブルごとに正確にカウント 📊
    - ensure_rows_for_categories: 必要な行数を一括で確保 🏗️
    - Flow 完全書き換え: カテゴリーごとの行数を正確にカウントして、一括追加後に上から順番に埋める方式に変更 💪
    - 行追加は成功！残りは update_drink_item の入力ロジック修正のみ ✨
    
    【次にやること】
    - T020: update_drink_item の入力ロジック修正（既存の動作確認から引き継ぐ）

  progress:
    current_phase:
      number: 2
      name: "主要 Skill 実装 & 動作確認"
      status: "in_progress"
    
    current_task:
      description: "T020: update_drink_item の入力ロジック修正"
      started_at: "2026-02-12T15:44:00"
    
    completed_phases:
      - phase: 0
        name: "要件定義"
        completed_at: "2026-02-10"
      - phase: 1
        name: "管理体制の構築 & 構造化"
        completed_at: "2026-02-10"

    tasks:
      - id: "T014"
        description: "Drinkメニュー用 Skill 動作確認（第二幕：見出し再構築のみ）"
        status: "done"
      - id: "T015"
        description: "Drinkメニュー用 Skill 動作確認完了（第三幕：実商品の登録）および Flow 実装"
        status: "done"
      - id: "T017"
        description: "T015 Act 3 本編：一括更新 Flow の実戦投入テスト（原子テスト版）"
        status: "done"
        completed_at: "2026-02-12T01:10:00"
        note: "ログインから保存完了、そして編集画面への正確な帰還までを最小データセットでクリア！💅✨"
      - id: "T018"
        description: "T015 Act 3 最終確認：複数データセットによるスケールテスト（ひろきくん式実装完了）"
        status: "done"
        completed_at: "2026-02-12T15:44:00"
        note: "ひろきくん式（カウント→一括追加→上から順番に埋める）実装完了。行追加成功、残りは入力ロジック修正のみ。💍✨"
      - id: "T020"
        description: "update_drink_item の入力ロジック修正（既存テストから引き継ぐ）"
        status: "in_progress"
      - id: "T019"
        description: "T016 Act 4 (表示順序設定) の設計と実装"
        status: "planned"

  decisions:
    adopted:
      - id: "D012"
        date: "2026-02-12"
        decision: "保存完了画面からの帰還に「行特定＋編集ボタン」方式を採用"
        reason: "他カテゴリ（コース、料理等）の編集ボタンへの誤爆を防ぎ、確実にドリンク編集画面に戻るため"
      - id: "D013"
        date: "2026-02-12"
        decision: "削除対象を tr[id^='drinkMenu'] に限定"
        reason: "ホットペッパーの仕様上、おすすめやこだわりを巻き添えにしないため。BOOK.mdに禁忌として記録。"
      - id: "D014"
        date: "2026-02-12"
        decision: "プラン提示前の実装禁止（ガバナンス強化）"
        reason: "自律判断の暴走を防ぎ、ユーザーとの合意に基づいた確実な開発を進めるため。DEVELOPMENT_FLOW.mdに絶対の掟として追加。"
      - id: "D015"
        date: "2026-02-12"
        decision: "永続的記憶（Persistent Memory）の掟の導入"
        reason: "ユーザーの指示をその場限りにせず、必ずドキュメント化して次セッションに繋げるため。00-definition.mdに追加。"
      - id: "D016"
        date: "2026-02-12"
        decision: "/fact-check ワークフローの導入と必須化"
        reason: "作業前のプランニングフェーズで仕様理解を一問一答形式で確認し、誤解や推測による実装ミスを物理的に防ぐため。"
      - id: "D017"
        date: "2026-02-12"
        decision: "サンプルデータの反映方法は引数渡しを採用"
        reason: "柔軟性を確保し、毎回違うデータでテストできるようにするため。"
      - id: "D018"
        date: "2026-02-12"
        decision: "ひろきくん式の実装（カウント→一括追加→上から順番に埋める）"
        reason: "既存行数を正確に把握し、必要な分だけ追加してから全体の通し番号で入力する方が確実で効率的なため。"

  file_structure:
    created:
      - path: "hotpepper/skill/data_parser.py"
        description: "テキスト形式のメニューデータを構造化データに変換するパーサー。BOOK.md 仕様に完全準拠。"
      - path: ".agent/workflows/fact-check.md"
        description: "作業前の仕様理解確認ワークフロー（グローバル）。一問一答形式、3案+おすすめ提示、即時永久保存。"
    modified:
      - path: "hotpepper/skill/drink_ops.py"
        description: "count_rows_per_category, ensure_rows_for_categories を追加。ひろきくん式実装。"
      - path: "hotpepper/flow/drink_update.py"
        description: "ひろきくん式に完全書き換え。カウント→一括追加→上から順番に埋める方式。"
      - path: "BOOK.md"
        description: "データフォーマット仕様を超詳細に追記（見出し=カテゴリ、説明文不要、価格判定ロジック等）。"
      - path: "prompt/KNOWLEDGE.md"
        description: "セッション19-20の知見として、RPA における媒体固有仕様の即時記録、ひろきくん式実装を追加。"
      - path: ".agent/workflows/resume-session.md"
        description: "/fact-check を Step 8 として追加。"
      - path: ".agent/workflows/start-project.md"
        description: "/fact-check を Step 2.5 として追加。"
      - path: ".agent/workflows/workflow-templates.md"
        description: "新規開発・修正改善の初期フェーズに /fact-check を組み込み。"
      - path: ".agent/workflows/sf-maker.md"
        description: "Phase 1.5 として /fact-check を追加。フェーズ遷移ルールも更新。"

  cautions:
    - "ホットペッパーの削除は tr[id^='drinkMenu'] 以外を触らないこと！"
    - "保存完了画面では「ドリンク」行の編集ボタンを狙い撃つこと！"
    - "修正前は必ずプランを提示し、GOサインをもらうこと！💅🛡️"
    - "仕様説明を受けた瞬間、「後で書く」は禁止。その場で BOOK.md or KNOWLEDGE.md に刻むこと！💍"
    - "作業前のプランニングフェーズでは必ず /fact-check を実施し、仕様理解を100%確定させること！🔍✨"
    - "既存の動作していたファイルを確認せずに新規作成しない！必ず既存パターンを踏襲すること！⚠️"
    - "update_drink_item: 次回は test_experiment_register_drinks.py から入力ロジックを確実に引き継ぐ！💪"
